server:
  port: 8002

spring:
  application:
    name: leyou-upload
  servlet:
    multipart:
      max-file-size: 5MB #限定文件上传大小

#将服务提供者注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: leyou-upload-8002 #定义微服务的名称
    prefer-ip-address: true #是否显示IP和端口
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.80.129:22122
